### ISSUE TITLE
Usage example doesn't work

### ISSUE THREAD

**Issue by aduggin** [babaskate/grunt-tenon#2]
Hi,

I tried running a test following the default options usage example.  This didn't work for me:

```
grunt.initConfig({
    tenon: {
        options: {
            apiKey: "API_KEY"
        },
        local: {
            urls: [
                'URL'
            ]
        }
    }
});
```

The following does work for me:

```
grunt.initConfig({
    tenon: {
      options: {
        apiKey: "API_KEY",
        urls: [
          'URL'
        ]
      },
      local: {
      }
    }
});
```

Removing local stopped it working.

Each time I ran the following command:
grunt tenon

cheers,
Al

**Comment by babaskate** [comment]
This has been fixed in v0.0.5, there's updated usage examples. URLs are a standalone property or can be kept as an option property
