### ISSUE TITLE
Instructions for urlService conflicts with urls

### ISSUE THREAD

**Issue by d-g-h** [babaskate/grunt-tenon#4]
https://github.com/babaskate/grunt-tenon/blame/66298e1db782f93fdc0bb0599c46184d97aaf796/README.md#L84

urlService [string], I believe this is suppose to refer to

> 
//If the site has a service that returns URLs to pages, hit the service to fetch the urls and pass to tenon

Maybe...The url of the file that contains a list of URLs?

The url [array] has the same instructions

https://github.com/babaskate/grunt-tenon/blame/66298e1db782f93fdc0bb0599c46184d97aaf796/README.md#L91

Correct if I'm wrong please. BTW, thanks for this.

**Comment by babaskate** [comment]
Sorry for the very slow reply. I've finally have some time to readdress some things:

The urlService is a custom service endpoint that must return JSON and has a `urls` property. This property is an `array` of object literals. An individual object literal has a property called, `path`, which is the path to a page. The path can be fully qualified or relative to the `httpBase`. The urlService path can also be relative to the httpBase or fully qualified.

I'll be updating the README to reflect this information. Hope this helps.

Thanks

**Comment by babaskate** [comment]
This has been update in the latest version 0.0.5
